{
  "error": "Cannot connect to server: HTTPConnectionPool(host='localhost', port=7410): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fff65e84b50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
}